### ISSUE TITLE
Bitdefender warns that makebin.exe is infected with a Trojan Virus

### ISSUE THREAD

**Issue by kwalt95** [gbdk-2020/gbdk-2020-sdcc#1]
Steps to replicate:

1. With a PC that has Windows 10 and Bitdefender on it, download and extract `sdcc-12539 binaries (patched)`.

2. Bitdefender will state it is disinfecting the file, and then will provide the following text after quarantining the file:

 _"The file D:\Downloads\sdcc-x86_64-w64-mingw32-20210711-12539--sms-gg-patched\sdcc\bin\makebin.exe is infected with Trojan.GenericKD.37738715 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean."_

**Comment by bbbbbr** [comment]
It is a false positive to the best of our knowledge.

Please see this Issue in the main GBDK-2020 repo:
https://github.com/gbdk-2020/gbdk-2020/issues/277

**Comment by bbbbbr** [comment]
makebin has been rebuilt (with minor, unrelated code changes: add `-yN` flag) and no longer seems to trigger virus warnings. The GBDK-2020 4.0.5 release has been updated with it.

See the 4.0.6 SDCC binary package.
